services:
 postgres:
  image: postgres
  container_name: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: root
   POSTGRES_USER: admin
   POSTGRES_DB: restaurants
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
 pgadmin:
  container_name: pgadmin
  image: dpage/pgadmin4
  restart: always
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: root
  ports:
   - "5050:80"
  volumes:
   - pgadmin:/var/lib/pgadmin
volumes:
 postgres_data:
 pgadmin:
